env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - google
parser: babel-eslint
parserOptions:
  allowImportExportEverywhere: true
  ecmaVersion: 2019
  sourceType: module
rules:
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: true
  max-len:
    - error
    - code: 120
  object-curly-spacing:
    - error
    - always
    - objectsInObjects: false
  require-jsdoc: 0
